language: java
jdk:
  - openjdk11

branches:
  only:
    - master



before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r complete *
  - mkdir -p deploy
  - mv complete.zip deploy/complete.zip

deploy:
  - provider: s3
    access_key_id: AKIA2Y4K7BDSLX7TWEZK

    secret_access_key: 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

    bucket: gt-webserver-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: AKIA2Y4K7BDSLX7TWEZK
    secret_access_key: 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
    bucket: gt-webserver-build
    key: complete.zip
    bundle_type: zip
    application: gt-webserver
    deployment_group: gt-webserver-group
    region: ap-northeast-2
    wait-until-deployed: true

# Travis CI 서버의 Home

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - a01021719359@gmail.com