language: java
jdk:
  - openjdk11

branches:
  only:
    - master



before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r complete *
  - mkdir -p deploy
  - mv complete.zip deploy/complete.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY

    secret_access_key: $AWS_SECRET_KEY

    bucket: gt-webserver-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

# Travis CI 서버의 Home

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - a01021719359@gmail.com