spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/portfolio1;MODE=MYSQL
    url: jdbc:h2:tcp://localhost/~/portfolio1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true

logging.level:
  org.hibernate.SQL: debug